version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: COUNT
      POSTGRES_PASSWORD: BOXES
      POSTGRES_DB: COUNTBOXES
    ports:
      - '5433:5433' # Mapeia a porta do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U COUNT']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://COUNT:BOXES@db:5433/COUNTBOXES # URL de conexão do Prisma
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev # Vai rodar as migrações no Dockerfile
    volumes:
      - .:/app

volumes:
  postgres_data:
