version: "3"

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-event"
    restart: always
    volumes:
      - ./database-event-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

volumes:
  database-event-api:
